version: '3.8'

services:
  # MongoDB service
  mongo:
    image: mongo:7
    container_name: ordertaker-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: ordertaker
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb
    networks:
      - ordertaker-network

  # Backend Node.js API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ordertaker-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:password123@mongo:27017/ordertaker?authSource=admin
      PORT: 5000
      FRONTEND_URL: http://localhost:3000
    volumes:
      - backend-uploads:/app/uploads
    depends_on:
      - mongo
    networks:
      - ordertaker-network

  # Next.js application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ordertaker-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
    depends_on:
      - backend
    networks:
      - ordertaker-network

networks:
  ordertaker-network:
    driver: bridge

volumes:
  mongo-data:
  mongo-config:
  backend-uploads:
